### ISSUE TITLE
200 antiphons get aligned, 500 don't.

### ISSUE THREAD

**Issue by hajicj** [Genome-of-Melody/chantlab_frontend#16]
Tested on aligning antiphons from D-KA Aug. LX (I was looking to produce a dendrogram to compare agaist Gevaert groups).

**Comment by lanzv** [comment]
The reason is the timeout limits -> solved by [chantlab_backend: Increase timeout limit for large alignments #21
](https://github.com/Genome-of-Melody/chantlab_backend/issues/21)

~ 500 chants for alignment is the limit due to the web browser storage limit (~5MB), the alignment object is then larger
Do we even want more aligned chants? It is impractical to compare this amount of chants and the browser rendering is very slow
