### ISSUE TITLE
Create Concatenated Alignment Page

### ISSUE THREAD

**Issue by lanzv** [Genome-of-Melody/chantlab_frontend#22]
- Add "concatenated" option next to "select/deselect all" on the chant list page
- Call alignment endpoint with the concatenated parameter as True
- Parse concatenated alignment and visualize it at the Concatenated Page
- Support all widgets on the alignment page

**Comment by hajicj** [comment]
Note: when processing in concatenation mode multiple chants with the same Cantus ID might be selected. In that case, only retain the chant with the longest melody from that Cantus ID (often in sources the other occurrences are just melodic incipits). This is a risk because one can also display and select these incomplete chants.
